apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: webapp
  template:
    metadata:
      labels:
        tag: webapp
    spec:
      containers:
        - name: webapp
          image: vchraf/webapp:6
          ports:
            - containerPort: 9772
          env:
            - name: REDIS_HOST
              value: redis-clusterip
            - name: REDIS_PORT
              value: '6379'
            - name: PG_HOST
              value: postgres-clusterip
            - name: PG_DB
              value: postgres
            - name: PG_USER
              value: admin
            - name: PG_PASSWORD
              value: admin
            - name: WORKER_ADRESS
              value: worker-clusterip
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    tag: webapp
  ports:
    - port: 9772
      targetPort: 9772
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-lb
# spec:
#   selector:
#     tag: webapp
#   ports:
#     - port: 9772
#       targetPort: 9772
#   type: LoadBalancer